[
{"message":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","level":"FATAL","type":"PLAYGROUND","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","log":"/tmp/tmp.ZrtubcFEVw"}
,
{"message":"Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:36 UTC] PHP Deprecated:  Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:36 UTC] PHP Deprecated:  Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:37 UTC] PHP Deprecated:  Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>chi</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","level":"NOTICE","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:37 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>chi</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:37 UTC] PHP Deprecated:  Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:45 UTC] PHP Deprecated:  Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:45 UTC] PHP Deprecated:  Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:46 UTC] PHP Deprecated:  Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>chi</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","level":"NOTICE","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:46 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>chi</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:46 UTC] PHP Deprecated:  Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:54 UTC] PHP Deprecated:  Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:54 UTC] PHP Deprecated:  Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:54 UTC] PHP Deprecated:  Function load_plugin_textdomain was called with an argument that is <strong>deprecated</strong> since version 2.7.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>chi</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","level":"NOTICE","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:54 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>chi</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","level":"DEPRECATED","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:33:54 UTC] PHP Deprecated:  Function register_sidebar_widget is <strong>deprecated</strong> since version 2.8.0! Use wp_register_sidebar_widget() instead. in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Uncaught Error: Call to a member function getName() on null in /wordpress/wp-content/plugins/catalogo/modules/Catalog.php:488","level":"FATAL","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:34:53 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /wordpress/wp-content/plugins/catalogo/modules/Catalog.php:488\nStack trace:\n#0 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(1171): CatalogoPluginColumnOperations->getIdFromName(Array, 'ref')\n#1 /wordpress/wp-content/plugins/catalogo/catalogo.php(494): CatalogoPluginCatalogData->getTypeColumns(Array, Array)\n#2 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#6 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#7 {main}\n  thrown in /wordpress/wp-content/plugins/catalogo/modules/Catalog.php on line 488","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: _mysql_data_types_cache.mysql_type.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE TABLE wp_catalogoplugin_column(\n                id int(11) NOT NULL AUTO_INCREMENT ,\n                name char(32) NOT NULL ,\n                description char(128) ,\n                id_column_definition int NOT NULL,\n                PRIMARY KEY ( `id`  ),\n                FOREIGN KEY (`id_column_definition`) REFERENCES wp_catalogoplugin_column_definition(`id`)\n                ) </p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, id, int(11)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, name, char(32)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, description, char(128)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, id_column_definition, int</li>\n<li>Executing: CREATE TABLE &quot;wp_catalogoplugin_column&quot; (\n&quot;id&quot; integer PRIMARY KEY AUTOINCREMENT NOT NULL ON CONFLICT REPLACE DEFAULT 0,\n&quot;name&quot; text NOT NULL ON CONFLICT REPLACE DEFAULT '' COLLATE NOCASE,\n&quot;description&quot; text COLLATE NOCASE,\n&quot;id_column_definition&quot; integer NOT NULL ON CONFLICT REPLACE DEFAULT 0) | (no parameters)</li>\n<li>Executing: CREATE  INDEX  &quot;wp_catalogoplugin_column__&quot; ON &quot;wp_catalogoplugin_column&quot; (&quot;&quot;) | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, wp_catalogoplugin_column__, </li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: _mysql_data_types_cache.mysql_type.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE wp...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(474): dbDelta(Array)\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(477): CatalogoPluginColumnOperations->createTable()\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query CREATE TABLE wp_catalogoplugin_column(\n                id int(11) NOT NULL AUTO_INCREMENT ,\n                name char(32) NOT NULL ,\n                description char(128) ,\n                id_column_definition int NOT NULL,\n                PRIMARY KEY ( `id`  ),\n                FOREIGN KEY (`id_column_definition`) REFERENCES wp_catalogoplugin_column_definition(`id`)\n                )  made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->createTable, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('ref', 'reference[4] NOT NULL',1)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,1) | parameters: ref, reference[4] NOT NULL</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('ref', 'reference[4] NOT NULL',1) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='ref'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: ref</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('ref')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='ref' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('label', 'label[50]',2)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,2) | parameters: label, label[50]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('label', 'label[50]',2) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='label'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: label</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('label')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='label' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('autor', 'autor[50]',3)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,3) | parameters: autor, autor[50]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('autor', 'autor[50]',3) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='autor'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: autor</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('autor')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='autor' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('title', 'title[50]',4)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,4) | parameters: title, title[50]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('title', 'title[50]',4) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='title'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: title</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('title')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='title' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('comment', 'comment[255]',5)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,5) | parameters: comment, comment[255]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('comment', 'comment[255]',5) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='comment'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: comment</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('comment')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='comment' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('storage', 'id of storage[2]',6)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,6) | parameters: storage, id of storage[2]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('storage', 'id of storage[2]',6) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='storage'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: storage</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('storage')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='storage' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: _mysql_data_types_cache.mysql_type.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE TABLE wp_catalogoplugin_type_columns(\n                id_type int(11) NOT NULL,\n                id_column int(11) NOT NULL,\n                PRIMARY KEY ( `id_type`, `id_column` ),\n                FOREIGN KEY (`id_type`) REFERENCES wp_catalogoplugin_type(`id`),\n                FOREIGN KEY (`id_column`) REFERENCES wp_catalogoplugin_column(`id`)\n                ) </p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_type_columns, id_type, int(11)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_type_columns, id_column, int(11)</li>\n<li>Executing: CREATE TABLE &quot;wp_catalogoplugin_type_columns&quot; (\n&quot;id_type&quot; integer NOT NULL ON CONFLICT REPLACE DEFAULT 0,\n&quot;id_column&quot; integer NOT NULL ON CONFLICT REPLACE DEFAULT 0,\nPRIMARY KEY (&quot;id_type&quot;, &quot;id_column&quot;)) | (no parameters)</li>\n<li>Executing: CREATE  INDEX  &quot;wp_catalogoplugin_type_columns__&quot; ON &quot;wp_catalogoplugin_type_columns&quot; (&quot;&quot;) | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_type_columns, wp_catalogoplugin_type_columns__, </li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: _mysql_data_types_cache.mysql_type.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE wp...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(638): dbDelta(Array)\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(493): CatalogoPluginTypeColumnsOperations->createTable()\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query CREATE TABLE wp_catalogoplugin_type_columns(\n                id_type int(11) NOT NULL,\n                id_column int(11) NOT NULL,\n                PRIMARY KEY ( `id_type`, `id_column` ),\n                FOREIGN KEY (`id_type`) REFERENCES wp_catalogoplugin_type(`id`),\n                FOREIGN KEY (`id_column`) REFERENCES wp_catalogoplugin_column(`id`)\n                )  made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginTypeColumnsOperations->createTable, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Uncaught Error: Call to a member function getName() on null in /wordpress/wp-content/plugins/catalogo/modules/Catalog.php:488","level":"FATAL","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:01 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /wordpress/wp-content/plugins/catalogo/modules/Catalog.php:488\nStack trace:\n#0 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(1171): CatalogoPluginColumnOperations->getIdFromName(Array, 'ref')\n#1 /wordpress/wp-content/plugins/catalogo/catalogo.php(494): CatalogoPluginCatalogData->getTypeColumns(Array, Array)\n#2 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#6 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#7 {main}\n  thrown in /wordpress/wp-content/plugins/catalogo/modules/Catalog.php on line 488","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: _mysql_data_types_cache.mysql_type.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE TABLE wp_catalogoplugin_column(\n                id int(11) NOT NULL AUTO_INCREMENT ,\n                name char(32) NOT NULL ,\n                description char(128) ,\n                id_column_definition int NOT NULL,\n                PRIMARY KEY ( `id`  ),\n                FOREIGN KEY (`id_column_definition`) REFERENCES wp_catalogoplugin_column_definition(`id`)\n                ) </p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, id, int(11)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, name, char(32)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, description, char(128)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, id_column_definition, int</li>\n<li>Executing: CREATE TABLE &quot;wp_catalogoplugin_column&quot; (\n&quot;id&quot; integer PRIMARY KEY AUTOINCREMENT NOT NULL ON CONFLICT REPLACE DEFAULT 0,\n&quot;name&quot; text NOT NULL ON CONFLICT REPLACE DEFAULT '' COLLATE NOCASE,\n&quot;description&quot; text COLLATE NOCASE,\n&quot;id_column_definition&quot; integer NOT NULL ON CONFLICT REPLACE DEFAULT 0) | (no parameters)</li>\n<li>Executing: CREATE  INDEX  &quot;wp_catalogoplugin_column__&quot; ON &quot;wp_catalogoplugin_column&quot; (&quot;&quot;) | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_column, wp_catalogoplugin_column__, </li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: _mysql_data_types_cache.mysql_type.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE wp...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(474): dbDelta(Array)\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(477): CatalogoPluginColumnOperations->createTable()\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query CREATE TABLE wp_catalogoplugin_column(\n                id int(11) NOT NULL AUTO_INCREMENT ,\n                name char(32) NOT NULL ,\n                description char(128) ,\n                id_column_definition int NOT NULL,\n                PRIMARY KEY ( `id`  ),\n                FOREIGN KEY (`id_column_definition`) REFERENCES wp_catalogoplugin_column_definition(`id`)\n                )  made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->createTable, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('ref', 'reference[4] NOT NULL',1)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,1) | parameters: ref, reference[4] NOT NULL</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('ref', 'reference[4] NOT NULL',1) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='ref'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: ref</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('ref')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='ref' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('label', 'label[50]',2)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,2) | parameters: label, label[50]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('label', 'label[50]',2) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='label'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: label</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('label')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='label' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('autor', 'autor[50]',3)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,3) | parameters: autor, autor[50]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('autor', 'autor[50]',3) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='autor'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: autor</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('autor')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='autor' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('title', 'title[50]',4)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,4) | parameters: title, title[50]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('title', 'title[50]',4) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='title'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: title</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('title')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='title' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('comment', 'comment[255]',5)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,5) | parameters: comment, comment[255]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('comment', 'comment[255]',5) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='comment'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: comment</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('comment')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='comment' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>insert into wp_catalogoplugin_column(name, description, id_column_definition) values('storage', 'id of storage[2]',6)</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: insert into wp_catalogoplugin_column(name, description, id_column_definition) values(:param0 , :param1 ,6) | parameters: storage, id of storage[2]</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(399): WP_SQLite_DB->query('insert into wp_...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(403): CatalogoPluginColumnOperations->insert(Object(CatalogoPluginColumn))\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query insert into wp_catalogoplugin_column(name, description, id_column_definition) values('storage', 'id of storage[2]',6) made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->insert, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>select * from wp_catalogoplugin_column where name='storage'</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: select * from wp_catalogoplugin_column where name=:param0  | parameters: storage</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_catalogoplugin_column.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('select * from w...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(448): wpdb->get_results('select * from w...')\n#3 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(404): CatalogoPluginColumnOperations->getByName('storage')\n#4 /wordpress/wp-content/plugins/catalogo/catalogo.php(481): CatalogoPluginColumnOperations->insertGet(Object(CatalogoPluginColumn))\n#5 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#9 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#10 {main}</pre>\n for query select * from wp_catalogoplugin_column where name='storage' made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginColumnOperations->insertGet, CatalogoPluginColumnOperations->getByName, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: _mysql_data_types_cache.mysql_type.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE TABLE wp_catalogoplugin_type_columns(\n                id_type int(11) NOT NULL,\n                id_column int(11) NOT NULL,\n                PRIMARY KEY ( `id_type`, `id_column` ),\n                FOREIGN KEY (`id_type`) REFERENCES wp_catalogoplugin_type(`id`),\n                FOREIGN KEY (`id_column`) REFERENCES wp_catalogoplugin_column(`id`)\n                ) </p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_type_columns, id_type, int(11)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_type_columns, id_column, int(11)</li>\n<li>Executing: CREATE TABLE &quot;wp_catalogoplugin_type_columns&quot; (\n&quot;id_type&quot; integer NOT NULL ON CONFLICT REPLACE DEFAULT 0,\n&quot;id_column&quot; integer NOT NULL ON CONFLICT REPLACE DEFAULT 0,\nPRIMARY KEY (&quot;id_type&quot;, &quot;id_column&quot;)) | (no parameters)</li>\n<li>Executing: CREATE  INDEX  &quot;wp_catalogoplugin_type_columns__&quot; ON &quot;wp_catalogoplugin_type_columns&quot; (&quot;&quot;) | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_catalogoplugin_type_columns, wp_catalogoplugin_type_columns__, </li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: _mysql_data_types_cache.mysql_type.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE wp...')\n#2 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(638): dbDelta(Array)\n#3 /wordpress/wp-content/plugins/catalogo/catalogo.php(493): CatalogoPluginTypeColumnsOperations->createTable()\n#4 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#8 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#9 {main}</pre>\n for query CREATE TABLE wp_catalogoplugin_type_columns(\n                id_type int(11) NOT NULL,\n                id_column int(11) NOT NULL,\n                PRIMARY KEY ( `id_type`, `id_column` ),\n                FOREIGN KEY (`id_type`) REFERENCES wp_catalogoplugin_type(`id`),\n                FOREIGN KEY (`id_column`) REFERENCES wp_catalogoplugin_column(`id`)\n                )  made by activate_plugin, do_action('activate_catalogo/catalogo.php'), WP_Hook->do_action, WP_Hook->apply_filters, catalogoPlugin_activationHook, CatalogoPluginTypeColumnsOperations->createTable, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"Uncaught Error: Call to a member function getName() on null in /wordpress/wp-content/plugins/catalogo/modules/Catalog.php:488","level":"FATAL","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:35:09 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /wordpress/wp-content/plugins/catalogo/modules/Catalog.php:488\nStack trace:\n#0 /wordpress/wp-content/plugins/catalogo/modules/Catalog.php(1171): CatalogoPluginColumnOperations->getIdFromName(Array, 'ref')\n#1 /wordpress/wp-content/plugins/catalogo/catalogo.php(494): CatalogoPluginCatalogData->getTypeColumns(Array, Array)\n#2 /wordpress/wp-includes/class-wp-hook.php(324): catalogoPlugin_activationHook(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_catalo...', false)\n#6 /internal/eval.php(20): activate_plugin('catalogo/catalo...')\n#7 {main}\n  thrown in /wordpress/wp-content/plugins/catalogo/modules/Catalog.php on line 488","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"include(/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php): Failed to open stream: No such file or directory in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:37:35 UTC] PHP Warning:  include(/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php): Failed to open stream: No such file or directory in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"include(): Failed opening '/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php' for inclusion (include_path='.:') in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:37:35 UTC] PHP Warning:  include(): Failed opening '/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php' for inclusion (include_path='.:') in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"include(/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php): Failed to open stream: No such file or directory in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:37:43 UTC] PHP Warning:  include(/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php): Failed to open stream: No such file or directory in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"include(): Failed opening '/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php' for inclusion (include_path='.:') in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:37:43 UTC] PHP Warning:  include(): Failed opening '/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php' for inclusion (include_path='.:') in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"include(/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php): Failed to open stream: No such file or directory in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:37:51 UTC] PHP Warning:  include(/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php): Failed to open stream: No such file or directory in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
,
{"message":"include(): Failed opening '/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php' for inclusion (include_path='.:') in /wordpress/wp-content/plugins/clear-booking/index.php on line 50","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"contact-form-7-shortcode-enabler","details":"[18-Apr-2025 13:37:51 UTC] PHP Warning:  include(): Failed opening '/wordpress/wp-content/plugins/clear-booking/includes/WP_Site_Health.php' for inclusion (include_path='.:') in /wordpress/wp-content/plugins/clear-booking/index.php on line 50\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #1 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"contact-form-7-shortcode-enabler\"},\"options\":{\"activate\":true}}) : Plugin /wordpress/wp-content/plugins/contact-form-7-shortcode-enabler could not be activated – WordPress exited with no error. Sometimes, when $_SERVER or site options are not configured correctly, WordPress exits early with a 301 redirect. Inspect the \"debug\" logs in the console for more details.\n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      ... 2 lines matching cause stack trace ...\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: Error: Plugin /wordpress/wp-content/plugins/contact-form-7-shortcode-enabler could not be activated – WordPress exited with no error. Sometimes, when $_SERVER or site options are not configured correctly, WordPress exits early with a 301 redirect. Inspect the \"debug\" logs in the console for more details.\n        at wr (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:119:51)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Object.gt [as installPlugin] (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:974:42)\n        at async g (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12517:30)\n        at async Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12446:23)\n        at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n        at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n        at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n        at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12)\n  }\n}\n\n","log":"/logs/plugins/c/contact-form-7-shortcode-enabler/error.json"}
]
