[
{"message":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","level":"FATAL","type":"PLAYGROUND","test":"asyncify-boot","plugin":"open-content-license-generator","details":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","log":"/tmp/tmp.RFkk4zRDSG"}
,
{"message":"Undefined array key \"tree_nodes\" in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3080","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:07 UTC] PHP Warning:  Undefined array key \"tree_nodes\" in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3080","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3081","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:07 UTC] PHP Warning:  Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3081","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3082","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:07 UTC] PHP Warning:  Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3082","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3083","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:07 UTC] PHP Warning:  Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3083","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Undefined array key \"tree_nodes\" in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3080","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:07 UTC] PHP Warning:  Undefined array key \"tree_nodes\" in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3080","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3081","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:07 UTC] PHP Warning:  Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3081","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3082","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:07 UTC] PHP Warning:  Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3082","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3083","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:07 UTC] PHP Warning:  Trying to access array offset on value of type null in /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php on line 3083","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_wpda_org_chart_tree.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:17 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, '/admin/images/', '/admin/assets/images/')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, :param0 , :param1 ) | parameters: /admin/images/, /admin/assets/images/</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_wpda_org_chart_tree.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/organization-chart/database/database.php(147): WP_SQLite_DB->query('update wp_wpda_...')\n#2 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(101): wpda_org_chart_database->update_urls()\n#3 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(55): wpda_org_chart->update_database()\n#4 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(31): wpda_org_chart->call_base_filters()\n#5 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(113): wpda_org_chart->__construct()\n#6 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#7 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('organization-ch...')\n#8 /internal/eval.php(20): activate_plugin('organization-ch...')\n#9 {main}</pre>\n for query update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, '/admin/images/', '/admin/assets/images/') made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/organization-chart/wpdevart_chart.php'), wpda_org_chart->__construct, wpda_org_chart->call_base_filters, wpda_org_chart->update_database, wpda_org_chart_database->update_urls, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_wpda_org_chart_tree.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:17 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, '\\\\/admin\\\\/images\\\\/', '\\\\/admin\\\\/assets\\\\/images\\\\/')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, :param0 , :param1 ) | parameters: \\/admin\\/images\\/, \\/admin\\/assets\\/images\\/</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_wpda_org_chart_tree.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/organization-chart/database/database.php(149): WP_SQLite_DB->query('update wp_wpda_...')\n#2 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(101): wpda_org_chart_database->update_urls()\n#3 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(55): wpda_org_chart->update_database()\n#4 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(31): wpda_org_chart->call_base_filters()\n#5 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(113): wpda_org_chart->__construct()\n#6 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#7 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('organization-ch...')\n#8 /internal/eval.php(20): activate_plugin('organization-ch...')\n#9 {main}</pre>\n for query update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, '\\\\/admin\\\\/images\\\\/', '\\\\/admin\\\\/assets\\\\/images\\\\/') made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/organization-chart/wpdevart_chart.php'), wpda_org_chart->__construct, wpda_org_chart->call_base_filters, wpda_org_chart->update_database, wpda_org_chart_database->update_urls, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_wpda_org_chart_tree.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:27 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, '/admin/images/', '/admin/assets/images/')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, :param0 , :param1 ) | parameters: /admin/images/, /admin/assets/images/</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_wpda_org_chart_tree.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/organization-chart/database/database.php(147): WP_SQLite_DB->query('update wp_wpda_...')\n#2 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(101): wpda_org_chart_database->update_urls()\n#3 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(55): wpda_org_chart->update_database()\n#4 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(31): wpda_org_chart->call_base_filters()\n#5 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(113): wpda_org_chart->__construct()\n#6 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#7 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('organization-ch...')\n#8 /internal/eval.php(20): activate_plugin('organization-ch...')\n#9 {main}</pre>\n for query update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, '/admin/images/', '/admin/assets/images/') made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/organization-chart/wpdevart_chart.php'), wpda_org_chart->__construct, wpda_org_chart->call_base_filters, wpda_org_chart->update_database, wpda_org_chart_database->update_urls, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_wpda_org_chart_tree.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:27 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, '\\\\/admin\\\\/images\\\\/', '\\\\/admin\\\\/assets\\\\/images\\\\/')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, :param0 , :param1 ) | parameters: \\/admin\\/images\\/, \\/admin\\/assets\\/images\\/</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_wpda_org_chart_tree.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/organization-chart/database/database.php(149): WP_SQLite_DB->query('update wp_wpda_...')\n#2 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(101): wpda_org_chart_database->update_urls()\n#3 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(55): wpda_org_chart->update_database()\n#4 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(31): wpda_org_chart->call_base_filters()\n#5 /wordpress/wp-content/plugins/organization-chart/wpdevart_chart.php(113): wpda_org_chart->__construct()\n#6 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#7 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('organization-ch...')\n#8 /internal/eval.php(20): activate_plugin('organization-ch...')\n#9 {main}</pre>\n for query update wp_wpda_org_chart_tree SET tree_nodes = replace(tree_nodes, '\\\\/admin\\\\/images\\\\/', '\\\\/admin\\\\/assets\\\\/images\\\\/') made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/organization-chart/wpdevart_chart.php'), wpda_org_chart->__construct, wpda_org_chart->call_base_filters, wpda_org_chart->update_database, wpda_org_chart_database->update_urls, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/osd-blog-search-widget/osd-blog-search-widget.php:102","level":"FATAL","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:25:56 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/osd-blog-search-widget/osd-blog-search-widget.php:102\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('osd-blog-search...')\n#2 /internal/eval.php(20): activate_plugin('osd-blog-search...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/osd-blog-search-widget/osd-blog-search-widget.php on line 102","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/osd-blog-search-widget/osd-blog-search-widget.php:102","level":"FATAL","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:26:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/osd-blog-search-widget/osd-blog-search-widget.php:102\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('osd-blog-search...')\n#2 /internal/eval.php(20): activate_plugin('osd-blog-search...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/osd-blog-search-widget/osd-blog-search-widget.php on line 102","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/osd-blog-search-widget/osd-blog-search-widget.php:102","level":"FATAL","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:26:11 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/osd-blog-search-widget/osd-blog-search-widget.php:102\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('osd-blog-search...')\n#2 /internal/eval.php(20): activate_plugin('osd-blog-search...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/osd-blog-search-widget/osd-blog-search-widget.php on line 102","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"openssl_pkey_export(): cannot get key from parameter 1 in /wordpress/wp-content/plugins/oauth2-provider/includes/functions.php on line 376","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:34 UTC] PHP Warning:  openssl_pkey_export(): cannot get key from parameter 1 in /wordpress/wp-content/plugins/oauth2-provider/includes/functions.php on line 376","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"openssl_pkey_get_details() expects parameter 1 to be resource, bool given in /wordpress/wp-content/plugins/oauth2-provider/includes/functions.php on line 381","level":"WARNING","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:34 UTC] PHP Warning:  openssl_pkey_get_details() expects parameter 1 to be resource, bool given in /wordpress/wp-content/plugins/oauth2-provider/includes/functions.php on line 381","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Trying to access array offset on value of type null in /wordpress/wp-content/plugins/oauth2-provider/includes/functions.php on line 382","level":"NOTICE","type":"PHP","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:34 UTC] PHP Notice:  Trying to access array offset on value of type null in /wordpress/wp-content/plugins/oauth2-provider/includes/functions.php on line 382","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_refresh_tokens MODIFY refresh_token VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(358): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_refresh_tokens MODIFY refresh_token VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_refresh_tokens MODIFY client_id VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(359): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_refresh_tokens MODIFY client_id VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_public_keys MODIFY client_id VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(361): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_public_keys MODIFY client_id VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_jwt MODIFY client_id VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(362): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_jwt MODIFY client_id VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_authorization_codes MODIFY client_id VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(363): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_authorization_codes MODIFY client_id VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown show type: KEYS FROM.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>SHOW KEYS FROM wp_oauth_access_tokens</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown show type: KEYS FROM.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SHOW KEYS FROM ...')\n#2 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(375): wpdb->get_results('SHOW KEYS FROM ...')\n#3 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#7 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#8 {main}</pre>\n for query SHOW KEYS FROM wp_oauth_access_tokens made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_access_tokens MODIFY access_token VARCHAR(1000);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(383): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_access_tokens MODIFY access_token VARCHAR(1000); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 duplicate column name: ap_generated.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_access_tokens ADD `ap_generated` VARCHAR( 32 ) AFTER \t`scope`</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_oauth_access_tokens, `AP_GENERATED`, varchar(32)</li>\n<li>Executing: ALTER TABLE wp_oauth_access_tokens ADD `ap_generated`   text  \t | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: ap_generated.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(391): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_access_tokens ADD `ap_generated` VARCHAR( 32 ) AFTER \t`scope` made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 duplicate column name: code_challenge.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_authorization_codes ADD `code_challenge` VARCHAR( 1000 ) AFTER `id_token`</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_oauth_authorization_codes, `CODE_CHALLENGE`, varchar(1000)</li>\n<li>Executing: ALTER TABLE wp_oauth_authorization_codes ADD `code_challenge`   text   | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: code_challenge.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(401): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_authorization_codes ADD `code_challenge` VARCHAR( 1000 ) AFTER `id_token` made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 duplicate column name: code_challenge_method.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:44 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_authorization_codes ADD `code_challenge_method` VARCHAR( 32 ) AFTER `id_token`</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_oauth_authorization_codes, `CODE_CHALLENGE_METHOD`, varchar(32)</li>\n<li>Executing: ALTER TABLE wp_oauth_authorization_codes ADD `code_challenge_method`   text   | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: code_challenge_method.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(411): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_authorization_codes ADD `code_challenge_method` VARCHAR( 32 ) AFTER `id_token` made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:53 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_refresh_tokens MODIFY refresh_token VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(358): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_refresh_tokens MODIFY refresh_token VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:53 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_refresh_tokens MODIFY client_id VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(359): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_refresh_tokens MODIFY client_id VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:53 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_public_keys MODIFY client_id VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(361): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_public_keys MODIFY client_id VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:53 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_jwt MODIFY client_id VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(362): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_jwt MODIFY client_id VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:53 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_authorization_codes MODIFY client_id VARCHAR(191);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(363): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_authorization_codes MODIFY client_id VARCHAR(191); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown show type: KEYS FROM.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:53 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>SHOW KEYS FROM wp_oauth_access_tokens</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown show type: KEYS FROM.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SHOW KEYS FROM ...')\n#2 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(375): wpdb->get_results('SHOW KEYS FROM ...')\n#3 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#7 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#8 {main}</pre>\n for query SHOW KEYS FROM wp_oauth_access_tokens made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"Unknown operation: MODIFY.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:53 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_access_tokens MODIFY access_token VARCHAR(1000);</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: MODIFY.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(383): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_access_tokens MODIFY access_token VARCHAR(1000); made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 duplicate column name: ap_generated.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:53 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_access_tokens ADD `ap_generated` VARCHAR( 32 ) AFTER \t`scope`</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_oauth_access_tokens, `AP_GENERATED`, varchar(32)</li>\n<li>Executing: ALTER TABLE wp_oauth_access_tokens ADD `ap_generated`   text  \t | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: ap_generated.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/oauth2-provider/wp-oauth-main.php(391): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): WO_Server->upgrade(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_oauth2...', false)\n#6 /internal/eval.php(20): activate_plugin('oauth2-provider...')\n#7 {main}</pre>\n for query ALTER TABLE wp_oauth_access_tokens ADD `ap_generated` VARCHAR( 32 ) AFTER \t`scope` made by activate_plugin, do_action('activate_oauth2-provider/wp-oauth-server.php'), WP_Hook->do_action, WP_Hook->apply_filters, WO_Server->upgrade, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/o/open-content-license-generator/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 duplicate column name: code_challenge.","level":"FATAL","type":"SQL","test":"asyncify-boot","plugin":"open-content-license-generator","details":"[24-Apr-2025 11:27:53 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_oauth_authorization_codes ADD `code_challenge` VARCHAR( 1000 ) AFTER `id_token`</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_oauth_authorization_codes, `CODE_CHALLENGE`, varchar(1000)</li>\n<li>Executing: ALTER TABLE wp_oauth_authorization_codes ADD `code_challenge`   text   | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: code_challenge.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpr\n","log":"/logs/plugins/o/open-content-license-generator/error.json"}
]
